//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.BookingPlaces = new HashSet<BookingPlace>();
            this.Payments = new HashSet<Payment>();
            this.ToDoLists = new HashSet<ToDoList>();
        }
    
        public int id { get; set; }
        public Nullable<int> BookingTypeId { get; set; }
        public Nullable<System.DateTime> TourStartDate { get; set; }
        public Nullable<System.DateTime> TourEndDate { get; set; }
        public Nullable<int> VehicalTypeID { get; set; }
        public Nullable<int> SeatingCapacity { get; set; }
        public string HiringCondition { get; set; }
        public Nullable<int> NoOfSeats { get; set; }
        public Nullable<int> Adults { get; set; }
        public Nullable<int> Children { get; set; }
        public string Transportation { get; set; }
        public string Food { get; set; }
        public string Accomodation { get; set; }
        public Nullable<bool> IsPerSeat { get; set; }
    
        public virtual Master Master { get; set; }
        public virtual Master Master1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingPlace> BookingPlaces { get; set; }
        public virtual Participant Participant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToDoList> ToDoLists { get; set; }
    }
}
