//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingPlace
    {
        public int id { get; set; }
        public int BookingID { get; set; }
        public int PlaceID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime LastMofiedDate { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Master Master { get; set; }
    }
}
