//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BTEntities : DbContext
    {
        public BTEntities()
            : base("name=BTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<BookingPlace> BookingPlaces { get; set; }
        public virtual DbSet<Master> Masters { get; set; }
        public virtual DbSet<MasterType> MasterTypes { get; set; }
        public virtual DbSet<MstRole> MstRoles { get; set; }
        public virtual DbSet<Package> Packages { get; set; }
        public virtual DbSet<PackagePlace> PackagePlaces { get; set; }
        public virtual DbSet<Participant> Participants { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<ToDoList> ToDoLists { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
